name: OrgOps Topology

on:
  pull_request:
  workflow_dispatch:

jobs:
  topology:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: orgops
        uses: orgops/oo-action@v1
        with:
          command: topology
          path: .

      - name: Show report path
        run: 'echo "Report: ${{ steps.orgops.outputs.report-path }}"'
